# Generated by Django 6.0.5 on 2026-05-21 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('customer_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='residential', max_length=50)),
                ('lead_status', models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('estimate_scheduled', 'Estimate Scheduled'), ('estimate_sent', 'Estimate Sent'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paid', 'Paid'), ('lost', 'Lost / Did Not Book')], default='new_lead', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('service_call', 'Service Call'), ('panel_upgrade', 'Panel / Service Upgrade'), ('lighting', 'Lighting'), ('troubleshooting', 'Troubleshooting'), ('new_install', 'New Installation'), ('commercial', 'Commercial Work'), ('industrial', 'Industrial Work'), ('other', 'Other')], default='service_call', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_completed', 'Site Visit Completed'), ('quote_needed', 'Quote Needed'), ('quote_sent', 'Quote Sent'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='new', max_length=50)),
                ('job_address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('site_visit_date', models.DateTimeField(blank=True, null=True)),
                ('quote_due_date', models.DateField(blank=True, null=True)),
                ('labor_notes', models.TextField(blank=True)),
                ('material_notes', models.TextField(blank=True)),
                ('code_notes', models.TextField(blank=True)),
                ('access_notes', models.TextField(blank=True)),
                ('estimated_labor_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.job')),
            ],
        ),
    ]
