# Generated by Django 6.0.5 on 2026-05-21 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_alter_careerapplication_experience_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(default='⚡', max_length=10)),
                ('category', models.CharField(default='Residential Service', max_length=100)),
                ('customer_description', models.TextField(help_text='This is what the customer sees on the estimate.')),
                ('internal_checklist', models.TextField(blank=True, help_text='Private material checklist, code notes, permits, utility notes, tools, etc.')),
                ('default_labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='site_visit_date',
            new_name='scheduled_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='access_notes',
            new_name='site_notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lead_status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='code_notes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='estimated_labor_hours',
        ),
        migrations.RemoveField(
            model_name='job',
            name='estimated_material_cost',
        ),
        migrations.RemoveField(
            model_name='job',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='labor_notes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quote_due_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobphoto',
            name='notes',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('estimate_sent', 'Estimate Sent'), ('approved', 'Approved'), ('completed', 'Completed'), ('paid', 'Paid')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('site_visit', 'Site Visit'), ('estimate_needed', 'Estimate Needed'), ('estimate_sent', 'Estimate Sent'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='new', max_length=50),
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('scope_of_work', models.TextField()),
                ('exclusions', models.TextField(blank=True, default='Does not include unforeseen repairs, drywall repair, painting, utility fees, permit fees, or additional work outside the listed scope unless stated in writing.')),
                ('terms', models.TextField(blank=True, default='Customer authorizes JCV Power Solutions to perform the listed work. Additional work, hidden conditions, code corrections, or customer-requested changes may result in additional charges.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('declined', 'Declined')], default='draft', max_length=50)),
                ('customer_signature_name', models.CharField(blank=True, max_length=100)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', max_length=50)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.estimate')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicetemplate'),
        ),
    ]
