# Generated by Django 6.0.5 on 2026-05-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_materialcatalog_alter_careerapplication_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmaterial',
            name='labor_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='jobmaterial',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=95.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobmaterial',
            name='labor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobmaterial',
            name='material_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('site_visit', 'Site Visit'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting_parts', 'Waiting on Parts'), ('estimate_sent', 'Estimate Sent'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='materialcatalog',
            name='labor_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost'), ('converted', 'Converted')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=50),
        ),
    ]
