# Generated by Django 6.0.5 on 2026-05-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobmaterial_labor_hours_jobmaterial_labor_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('site_visit', 'Site Visit'), ('estimate_needed', 'Estimate Needed'), ('estimate_sent', 'Estimate Sent'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting_parts', 'Waiting on Parts'), ('completed', 'Completed'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='new', max_length=50),
        ),
    ]
