# Generated by Django 6.0.5 on 2026-05-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_job_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobmaterial',
            options={'ordering': ['material__name'], 'verbose_name': 'Job Material', 'verbose_name_plural': 'Job Materials'},
        ),
        migrations.AlterModelOptions(
            name='jobnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='materialcatalog',
            options={'ordering': ['name'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='servicetemplate',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='servicetemplatematerial',
            options={'ordering': ['service_template__category', 'service_template__name', 'material__name'], 'verbose_name': 'Service Template Material', 'verbose_name_plural': 'Service Template Materials'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'due_date', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='servicetemplatematerial',
            unique_together={('service_template', 'material')},
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('material', 'Material'), ('labor', 'Labor'), ('service', 'Service'), ('fee', 'Fee'), ('discount', 'Discount')], default='material', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.estimate')),
                ('source_job_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_line_items', to='core.jobmaterial')),
            ],
            options={
                'verbose_name': 'Estimate Line Item',
                'verbose_name_plural': 'Estimate Line Items',
                'ordering': ['id'],
            },
        ),
    ]
