# Generated by Django 6.0.5 on 2026-05-24 22:18

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_estimate_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmaterial',
            name='material_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.35'), max_digits=5),
        ),
        migrations.AddField(
            model_name='jobmaterial',
            name='material_sell_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobmaterial',
            name='sell_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='estimated_material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('110.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='material_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.35'), max_digits=5),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='permit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobmaterial',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('110.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
