# Generated by Django 6.0.5 on 2026-05-24 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobmaterial_material_markup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('estimate', 'Estimate'), ('pricing', 'Pricing'), ('materials', 'Materials'), ('scope', 'Scope of Work'), ('website', 'Website Content'), ('service_template', 'Service Template'), ('job', 'Job'), ('general', 'General')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='pending', max_length=50)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('suggestion', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='core.customer')),
                ('related_estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='core.estimate')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='core.job')),
                ('related_service_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='core.servicetemplate')),
            ],
            options={
                'verbose_name': 'AI Suggestion',
                'verbose_name_plural': 'AI Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
