# Generated by Django 6.0.5 on 2026-05-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aisuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestion',
            name='action_payload',
            field=models.JSONField(blank=True, help_text='Structured data the apply engine can use.', null=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='action_type',
            field=models.CharField(blank=True, help_text='What this suggestion can apply, such as update_pricing, create_service_page, create_task, update_estimate_scope.', max_length=100, null=True),
        ),
    ]
