# Generated by Django 6.0.5 on 2026-05-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aisuggestion_action_payload_aisuggestion_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('applied', 'Applied'), ('pushed', 'Pushed'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Command',
                'verbose_name_plural': 'AI Commands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICodeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('action', models.CharField(choices=[('create', 'Create'), ('replace', 'Replace'), ('delete', 'Delete')], default='replace', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('proposed_content', models.TextField(blank=True, null=True)),
                ('original_content', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_changes', to='core.aicommand')),
            ],
            options={
                'verbose_name': 'AI Code Change',
                'verbose_name_plural': 'AI Code Changes',
                'ordering': ['command', 'file_path'],
            },
        ),
    ]
