# Generated by Django 6.0.5 on 2026-06-11 22:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aicommand_aicodechange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicodechange',
            options={'ordering': ['command', 'file_path']},
        ),
        migrations.AlterModelOptions(
            name='aicommand',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='aisuggestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicodechange',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='aicommand',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('pushed', 'Pushed')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='action_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='action_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='related_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='related_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estimate'),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.job'),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='related_service_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicetemplate'),
        ),
        migrations.AlterField(
            model_name='jobmaterial',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('95.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobmaterial',
            name='material_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('95.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='material_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
