# Generated by Django 6.0.5 on 2026-06-12 00:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_aicodechange_options_alter_aicommand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcatalog',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='material_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='supplier_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
