# Generated by Django 6.0.5 on 2026-06-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_materialcatalog_last_price_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcatalog',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
