# Generated by Django 6.0.5 on 2026-06-12 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_materialcatalog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarvisJobReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='What the user asked JARVIS to analyze or build.')),
                ('summary', models.TextField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, default=dict, help_text='JARVIS recommended add/remove/update material actions.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('partially_applied', 'Partially Applied'), ('applied', 'Applied'), ('ignored', 'Ignored')], default='reviewed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jarvis_reviews', to='core.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
